version: '3.1'

services:
  app:
    build: .
    image: afmpro-front-image
    container_name: afmpro-front
    restart: always
    networks:
      - proxynet

networks:
  proxynet:
    external: true
