# version: '3.1'

# services:
#   app:
#     build: .
#     image: afmpro-front-image
#     container_name: afmpro-front
#     restart: always
#     networks:
#       - proxynet

# networks:
#   proxynet:
#     external: true

services:
  onayconsulting-frontend:
    image: ghcr.io/threestepsllc/acp-front:${IMAGE_TAG}
    container_name: onayconsulting-frontend
    restart: always
    ports:
      - "127.0.0.1:3010:3000"
    networks:
      - proxynet

networks:
  proxynet:
    external: true
