import React, { HTMLProps, ReactNode } from "react";
import Head from "next/head";
import Footer from "@/components/lib/Footer";
import Navbar from "@/components/lib/Navbar";

interface LayoutProps extends HTMLProps<HTMLDivElement> {
  children: ReactNode;
  title: string;
}

const Layout = ({ children, title, ...props }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{`${title} | ONAY Consulting`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
  
      <div {...props}>
        <Navbar />
        <main className="relative">{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;